### ISSUE TITLE
Flatiron School page issue

### ISSUE THREAD

**Issue by oznuren** [learn-co-curriculum/phase-1-javascript-variables-lab#20]
I couldn't register for the Flatiron's page, I was getting the error page whenever I tried to. So I completed the assignment through GitHub.

**Comment by lizbur10** [comment]
Hi @oznuren! Sorry to hear that! If you're still having problems getting logged in, your best bet is to check in with your instructor or cohort lead, or to use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

Good luck!
